### PR TITLE
Fix sidebar

### PR DESCRIPTION
**Pull request by sghung**
The sidebar has javascript that was causing problems due to how it hijacked the anchor events. It can be simplified. In addition, removed the animation (Kim is okay with that) and removed gettingstarted.html (talked to Sarah on that) to make the sidebar more consistent.

**head.html**
- Remove the base href. That causes a lot of issues as it prevents Jekyll’s table of contents from working since it messes up the anchors. Even beyond the table of contents, this affects the user of anchors in general, so it should not be used
- This fix requires topbar.html to be updated to use <a class="navbar-brand" href="{{ site.baseurl | append:  '/' }}"> instead

**docs.js**
- I removed a lot of the existing code there because it was used for the sidebar. The bootstrap list group handles most of this, there’s no reason to code it ourselves. In addition, it was causing issues because the query is too general (i.e. using “not”) so it can cause unintended hijacking of the anchor. This code caused grief when implementing the tabs in docs (tabs to be added after this PR goes in)
- To test this, I clicked on all the first level ones, ones that have a submenu, and ones that have a third level of submenus to ensure it syncs up correctly

**docs.html**
- Completely removed the existing logic to make it simpler and to work with the updated docs.js
- Verified that the behaviour is the same

**docs.css**
- Confirmed with Kim that the transition in opening the sidebar items can be removed. It looks less glitchy with it gone (especially during a sync)

The getting started page was removed, as it was deemed not necessary, so it redirects to the overview page now.

### CODE REVIEW

**Comment by sghung** [comment]
I will let Andrew know on slack to review this too, since I want someone to look over the code too

**Comment by sishida** [comment]
As far as I can tell, things look good. However, I will refrain from approving until after we create the 0.10.0 branch. :)

Also...I see all files in the `images/card` subfolder are being deleted. Should we just delete the whole subfolder?

**Comment by sghung** [comment]
@sishida I deleted the entire folder for card, it doesn't show on the github review, not sure why

**Comment by micgibso** [comment]
@sghung @makandre Do we want this in for 0.12.0? I see it's now got a couple of merge conflicts too.

**Pull request merged**
