### PR TITLE
[WIP not for 0.8.0] Instructions to update codewind on che

### PR DESCRIPTION
**Pull request by j-c-berger**
Signed-off-by: Jacob Berger <jacob.berger@ibm.com>

PR for issue 1045 from `eclipse/codewind`: https://github.com/eclipse/codewind/issues/1045

@johnmcollier, please review and let me know if there's anything else I can do. 

Thanks.

### CODE REVIEW

**Comment by johnmcollier** [comment]
@j-c-berger Changes look good to me. @jagrag is going to test it and once he gives his OK I'll merge

**Comment by j-c-berger** [comment]
@johnmcollier, perfect, thank you!

**Comment by j-c-berger** [comment]
@johnmcollier @jagrag, checking to see the status on this PR. Did it pass all tests? Ready to merge?

**Comment by sishida** [comment]
Jag, John, and ID agreed to not include this issue in 0.7.0. Release to be determined.

**Comment by sishida** [comment]
@j-c-berger Hi, Jake, Do you happen to know if this PR should go in for 0.8.0? If not, I'm wondering if I should just include this content as part of my Che tutorial restructure work. Please let me know. Thanks!

**Comment by sishida** [comment]
Jag, John, and ID agreed to not include this issue in 0.8.0. Release to be determined.

**Pull request closed without merging**
