### PR TITLE
[WIP]: Made new doc for application status

### PR DESCRIPTION
**Pull request by j-c-berger**
Signed-off-by: Jacob Berger <jacob.berger@ibm.com>

For issue #2117: https://github.com/eclipse/codewind/issues/2117

I drafted up this new doc for the work we added to troubleshooting for #1812. I mostly included the new content we added to troubleshooting for 1812. We can add much more content to this new doc, however much we see fit. 

As far as the doc's title, description, keywords, and placement in the TOC, I'm not attached to anything that I drafted here. This is simply a starting point so we can begin drafting the content that we need. 

@rajivnathan, thank you for taking the initiative on this and please review whenever you have time. Thanks.

### CODE REVIEW

**Comment by j-c-berger** [comment]
@rajivnathan, hey Rajiv, I'm touching base to see if you've had the chance to look at this PR. I know we mentioned hoping to get it done by 0.10.0. 

Let me know what you think, and I'm good to hold off for 0.11.0. Thanks!

**Comment by rajivnathan** [comment]
@j-c-berger Elson pointed out that we have this doc already: https://www.eclipse.org/codewind/checkingstatuses.html

So I figured it made sense to use that article as the starting point. I added some changes to it and modified the troubleshooting sections as well. PR here: https://github.com/eclipse/codewind-docs/pull/490

**Comment by j-c-berger** [comment]
@rajivnathan, cool, thanks. I'll take a look at that soon and get back with any changes (if necessary) today or tomorrow.

**Comment by j-c-berger** [comment]
Closing this PR, because #490 is for issue #2117, see this link: https://github.com/eclipse/codewind-docs/pull/490

**Comment by j-c-berger** [comment]
Closing this PR, because #490 is for issue #2117, see this link: https://github.com/eclipse/codewind-docs/pull/490

**Pull request closed without merging**
