### PR TITLE
fixes landing page renders incorrectly on wider screens

### PR DESCRIPTION
**Pull request by travis1111**
Fixes landing page rendering issue on wide screen (wider than 1920).

https://github.com/eclipse/codewind/issues/652

Signed-off-by: tiaoyuw <tiaoyuw@ca.ibm.com>

### CODE REVIEW

**Comment by sishida** [comment]
@travis1111 Thanks so much for your work on this! Who would you like me to assign as reviewer? I don't know a ton about HTML or CSS, so I don't think I'd make the best reviewer for this. 😅Thanks again and please let me know!

**Comment by travis1111** [comment]
@sishida Steven will be reviewing it :-)

**Comment by micgibso** [comment]
@sghung Could you take a look please? thx!

**Comment by sghung** [comment]
@travis1111 this is what I see when I use the chrome dev tools for phone sizes:
image

How did you test the phone scenario?

**Pull request closed without merging**
