### PR TITLE
adding appsody project screenshot

### PR DESCRIPTION
**Pull request by j-c-berger**
image for issue #712, https://github.com/eclipse/codewind/issues/712, linking to the image will be in a subsequent PR. 

Signed-off-by: Jacob Berger <jacob.berger@ibm.com>

### CODE REVIEW

**Comment by j-c-berger** [comment]
@tetchel,  would you please confirm from a dev's standpoint that this image is sufficient for the doc? 

I'm happy to make as many changes as necessary. Thanks!

**Comment by j-c-berger** [comment]
@tetchel , thank you for looking at this for me. I saw Michael did the documentation for the issue, and he wrote about Appsody projects in the doc `mdt-vsc-importedprojects.md` https://github.com/eclipse/codewind-docs/blob/master/docs/_documentations/mdt-vsc-importedprojects.md

This is what he wrote for Appsody projects:
```If you have an existing Appsody project, or a project that you want to add to Codewind as an Appsody project, select the corresponding Appsody project type and, if applicable, the Appsody stack when adding the project. For more information about Appsody and Appsody stacks, see https://appsody.dev.```

Therefore, I thought the image needed to show the different Appsody projects available in VS Code. I must have misunderstood. I'm not quite show how to depict the bind in an image. 

I looked  at `news05.md` https://github.com/eclipse/codewind-docs/blob/master/docs/_news/news05.md 

I see that it doesn't directly mention Appsody bind. It simply links to `Adding existing projects` which only has the above content Michael wrote. So maybe the content needs to include more detail on Appsody binding as well?

**Comment by tetchel** [comment]
Yes, the 'add existing project' is the 'bind' flow. The scenario described is
- make sure an Appsody template repository is enabled
- create an appsody project using codewind or the appsody command-line
- if the project was created using codewind, remove it from codewind
- run the Add Existing Project command
- select the appsody project
- * when Codewind asks for the project type, select the corresponding appsody project type
- the project will now work correctly as an appsody project
Previously, the starred step was not possible, because the appsody project types would not show up, you could only add "codewind" projects, which would not work for appsody.

**Comment by j-c-berger** [comment]
Closing this PR because screenshots/images/gifs issue will go to Becca Bau (Codewind Advocate) instead of ID team.

**Pull request closed without merging**
