### PR TITLE
Adding ROKS file

### PR DESCRIPTION
**Pull request by sishida**
Signed-off-by: Sarah Ishida <sishida@us.ibm.com>

Adding new file, Setting up OpenShift on IKS (ROKS) for Codewind, to documentation.

### CODE REVIEW

**Comment by sishida** [comment]
@johnmcollier Hi, John, I edited the file that we had in the wiki to prepare to add it to the docs page on Codewind.dev.

Here are some things we should still work on...
- I noticed we need external links to the links originally found in the third prerequisite and step 7 of **Setting up the NFS Server**.
- I removed the images because those will also need to be added to the `codewind-docs` repo.
- What is the `Codewind` repo issue that we should associated with this file?

Thanks!

**Comment by johnmcollier** [comment]
@sishida Thanks!
- For the first external link, it can be removed, it's not needed for our docs.
- For the second link, it is needed, so I'll get a PR up to add it
- No Codewind issue open currently, let me open one

**Comment by jagraj** [comment]
@johnmcollier 
Where does this file (che-nfs-pv.yaml )exist for the user.?

**Comment by jagraj** [comment]
@johnmcollier 
Got into this issue, even after disabling default storage it is bounded to ibm block storage rather to NFS storage that I created.

```
 oc get pv,pvc
NAME                                                        CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM                      STORAGECLASS       REASON    AGE
persistentvolume/che-data                                   1Gi        RWO            Recycle          Available                                                           3m
persistentvolume/che-workspace1                             1Gi        RWO            Recycle          Available                                                           3m
persistentvolume/che-workspace2                             1Gi        RWO            Recycle          Available                                                           3m
persistentvolume/che-workspace3                             1Gi        RWO            Recycle          Available                                                           3m
persistentvolume/che-workspace4                             1Gi        RWO            Recycle          Available                                                           3m
persistentvolume/che-workspace5                             1Gi        RWO            Recycle          Available                                                           3m
persistentvolume/pvc-e896b93d-d58d-11e9-b73a-d21b266726ac   20Gi       RWX            Delete           Bound       default/registry-backing   ibmc-file-bronze             4d

NAME                                    STATUS    VOLUME    CAPACITY   ACCESS MODES   STORAGECLASS        AGE
persistentvolumeclaim/che-data-volume   Pending                                       ibmc-block-bronze   1m
```

```
oc get sc
NAME                          PROVISIONER         AGE
default                       ibm.io/ibmc-file    4d
ibmc-block-bronze (default)   ibm.io/ibmc-block   4d
ibmc-block-custom             ibm.io/ibmc-block   4d
ibmc-block-gold               ibm.io/ibmc-block   4d
ibmc-block-retain-bronze      ibm.io/ibmc-block   4d
ibmc-block-retain-custom      ibm.io/ibmc-block   4d
ibmc-block-retain-gold        ibm.io/ibmc-block   4d
ibmc-block-retain-silver      ibm.io/ibmc-block   4d
ibmc-block-silver             ibm.io/ibmc-block   4d
ibmc-file-bronze              ibm.io/ibmc-file    4d
ibmc-file-custom              ibm.io/ibmc-file    4d
ibmc-file-gold                ibm.io/ibmc-file    4d
ibmc-file-retain-bronze       ibm.io/ibmc-file    4d
ibmc-file-retain-custom       ibm.io/ibmc-file    4d
ibmc-file-retain-gold         ibm.io/ibmc-file    4d
ibmc-file-retain-silver       ibm.io/ibmc-file    4d
ibmc-file-silver              ibm.io/ibmc-file    4d
```

**Comment by johnmcollier** [comment]
@jagraj I'll need to upload the yaml file to the codewind-che repo, let me do that now

For the PV issue, you need to do the following to disable the IBM File Storageclass:

Disable the IBM Block Storage storageclass:
```
kubectl patch storageclass ibmc-block-bronze -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"false"}}}'
```

@sishida Can you add the above as step 9? Thanks!

**Comment by jagraj** [comment]
I am all good once these changes are delivered. Thanks John and Sarah. 
I was able to Install Codewind on IKS successfully.

**Comment by sishida** [comment]
Hi, team, I have added the new step 9.

Also, @johnmcollier Could you please add the link on step 7 of "Setting up the NFS Server" after we merge this PR?

Thanks!

**Comment by johnmcollier** [comment]
@sishida The link is https://github.com/eclipse/codewind-che-plugin/blob/master/setup/nfs/nfs-pv.yaml

@jagraj Any concerns about merging?

**Pull request merged**
