### PR TITLE
New Landing Page

### PR DESCRIPTION
**Pull request by jcockbain**
## What type of PR is this ? 

- [ ] Bug fix
- [x] Enhancement

## What does this PR do ?

- Adds new landing page at `/codewind/learn`. 

> This will now be done in a follow-up PR: The old getting started URL (`/codewind/gettingstarted`) is redirected to this page (throough new dependency https://github.com/jekyll/jekyll-redirect-from).The existing `gettingstarted` file has been renamed to `gettingstarted-overview` to avoid a clash.

- Moves docs-sidebar into its own file under `/includes` so it can be used both in the `/docs` layout with processed markdown files, and in the new `learn` layout which contains a HTML file with the sidebar. 

- Adds a `_data/videos.yml` to store data on the Codewind videos. I did have a partially working branch using the Youtube API to dynamically get video data but it felt like too much a heavyweight addition for a static site at this stage.

- Moves the objectives in the guides into an array in the frontmatter of the file, and then uses these to populate both the page itself, and its card on the `/Learn` page.

## Which issue(s) does this PR fix ?

https://github.com/eclipse/codewind/issues/2594
https://github.com/eclipse/codewind/issues/2591

## Does this PR require a documentation change ?

I don't believe so.

## Any special notes for your reviewer ?

Changes are deployed to https://jcockbain.github.io/codewind-docs/learn.html.

### CODE REVIEW

**Comment by MelHopper** [comment]
Screenshot 2020-05-26 at 10 31 08

'Callout with Header
This is an HTML element'

The PR with this change can be seen on the test website https://jcockbain.github.io/codewind-docs/learn.html.

**Comment by MelHopper** [comment]
Titles for 'Blogs', 'Guides' and 'Videos' need to:
- link to the respective pages
- be changed to the blue branded colour to indicate they are clickable links

**Comment by MelHopper** [comment]
Question: Did we get Design input on the change of the sizing of the font on the page?

**Comment by MelHopper** [comment]
@micgibso please can you add me as reviewer? Many Thanks!

**Comment by jcockbain** [comment]
> Question: Did we get Design input on the change of the sizing of the font on the page?

Not yet no, it was suggested in feedback from the Portal squad to emphasise it as a title page. I can present both to design and we could get feedback?

The test callouts should now be removed from the deployed version, and the titles shown as clickable links.

**Comment by MelHopper** [comment]
> > Question: Did we get Design input on the change of the sizing of the font on the page?
> 
> Not yet no, it was suggested in feedback from the Portal squad to emphasise it as a title page. I can present both to design and we could get feedback?
> 
> The test callouts should now be removed from the deployed version, and the titles shown as clickable links.

Yes please to a review - @kimholmes please can you review the current version of the landing page at https://jcockbain.github.io/codewind-docs/learn.html 
In particular, the new size of the font that Portal squad requested be implemented? many thanks

**Comment by jcockbain** [comment]
Just noticed a bug in the new page in Safari, working on a fix now.

image

**Comment by kimholmes** [comment]
Here are some last adjustments that I see on the page:
FED_ImplementationSpec

Final mock-up for reference:
Docs_Landing4

**Comment by jcockbain** [comment]
@kimholmes - I've attempted to resolve the majority of adjustments, committed my changes and redeployed to  https://jcockbain.github.io/codewind-docs/learn.html. Let me know what you think. 

Some spacings aren't exact but I've attempted to make it as similar as I could.

**Comment by kimholmes** [comment]
@jcockbain This looks great James. Is it possible to left align the IDE download buttons inside the two tiles?
image

**Comment by jcockbain** [comment]
@kimholmes left aligning them is no problem, I can add that now. 

I did have a go at aligning the download icon to the right within the buttons, and found that hard without making the buttons less responsive with page resizing. Is that important, or are the buttons themselves sufficient as they are?

**Comment by kimholmes** [comment]
Thanks @jcockbain I prefer the second screenshot with the buttons left aligned.
The VSCode button got a little wonky though. Looks like the text is running into the icon. 
But I guess they are good to go!

**Comment by jcockbain** [comment]
Oops, that was a left over from me trying to align the icons to the right... won't actually be in there! 

Thanks, will make that final change to align left now.

**Comment by jcockbain** [comment]
@kimholmes I've updated with left aligned buttons, minus the wonky VSCode.

**Comment by sghung** [comment]
If you decrease the size, the "Lean" link can be hidden by the codewind logo, then if you try to click on it, you click the codewind logo instead

image

**Comment by jcockbain** [comment]
Thanks for the helpful comments @sghung. Here are my thoughts on each: 

1. This is an existing issue with the navbar, accentuated slightly by "docs" being changed to "learn" and therefore 2 more letters. I can do the same with the deployed version. I can attempt to fix as part of this PR or raise it as a separate issue and fix on its own?

image

2. Have pushed with capitals. 

3. Interesting, I'll investigate this. Thanks, that's a good spot. Do we have anything set up to test the behaviour once we copy the code into eclipse repo? 

6. Great point, Mel did mention this when it came up. Seems like the ideal is to generate the link to latest release. If we move onto version-specific docs in future, would we then have the user version? As a workaround for now I could set the version in the site config and make sure whenever a release branch is cut this is manually updated?

**Comment by kimholmes** [comment]
@jcockbain @sghung I think the top nav of the page being covered up by the logo is an edge case. I wouldn't spend too much time worrying about it. That's just my $.02!

**Comment by sghung** [comment]
@jcockbain @kimholmes I agree, that Docs being cut off might be an edge case. I was just thinking that if it got to that size, to switch over to the mobile menu, but honestly it's at a dimension that people may not care about

The best way to simulate the eclipse repo (I should have documented this in our onboarding box note), is to do what `build.sh` does. That script creates an apache server and the static files are copied into it. The `build.sh` has found issues before that were missed when running in Jekyll. For example, Jekyll will deal with re-directing <my file name>.html to <my file name>, but eclipse.org and apache do not. Eclipse.org *should* be using apache but also note that we cannot use .htaccess to modify the redirect :(

I think the workaround to keep track of the version in our docs should be okay. We just need to remember to update that each time we release, otherwise that file won't be correct. I'm also not entirely sure when that file gets generated...it might be DCUT and might be closer to GA, so you'd need to find out when that file is typically available. If there is an automated way to get past this, it would be good, so it's one less thing to worry about.

**Comment by jcockbain** [comment]
Thanks @sghung, @kimholmes. 

I'll have a go with the Apache server for the redirect. I've been in that area anyway today looking at setting up a Github Action.

Ok, sounds good on the Che link. I'll get the workaround ready and then see if I can find out more from a Che side.

**Comment by jcockbain** [comment]
@sghung - when you generated the above html for `getting-started.html`, were you using the `serve.sh` script? I get the same with `serve.sh`, but when I use the Docker Command for compiling the files from `build.sh` I get: 

```html
<!DOCTYPE html>
<html lang="en-US">
  <meta charset="utf-8">
  <title>Redirecting&hellip;</title>
  <link rel="canonical" href="/codewind/learn.html">
  <script>location="/codewind/learn.html"</script>
  <meta http-equiv="refresh" content="0; url=/codewind/learn.html">
  <meta name="robots" content="noindex">
  <h1>Redirecting&hellip;</h1>
  <a href="/codewind/learn.html">Click here if you are not redirected.</a>
</html>
```

Which when copied into an Apache container redirects correctly. Does that mean it should work when copied to the Eclipse repo?

**Comment by sghung** [comment]
@jcockbain I was using `serve.sh`, if it does work with `build.sh`, then the docs for publishing needs to be updated to ensure that script is used. Or, we could even have a `prepareForPublish.sh` script if we want to make it more clear

**Comment by jcockbain** [comment]
Good point @sghung. If we fix https://github.com/eclipse/codewind/issues/2717 won't it be that `./serve.sh` and `./build.sh` follow the same behaviour? 

I'll have a look around and work out what I think the best course of action is. You're right, as it is, it could lead to redirects not working in the published build.

**Comment by sghung** [comment]
Issue 2717 is talking about the staging server hosted internally. It isn't the same as `serve.sh` and `build.sh` having the same behaviour, although doing that would be a great idea. If `serve.sh` isn't as accurate as the apache server we'd eventually be using, then it should be changed to be more like `build.sh`

**Pull request merged**
