### PR TITLE
Remote install using the install.sh script

### PR DESCRIPTION
**Pull request by micgibso**
Signed-off-by: micgibso <MICGIBSO@uk.ibm.com>

PR for https://github.com/eclipse/codewind/issues/2464 using install.sh script.

### CODE REVIEW

**Comment by micgibso** [comment]
@markcor11 @AndyRWatson  Please review, thx.

**Comment by AndyRWatson** [comment]
The line "To install the Codewind operator in your cloud, follow the instructions in the codewind-operator readme." is not relevant in the git clone section.

It would be valid to highlight more detailed information on the install process can be found in the codewind-operator README.md  https://github.com/eclipse/codewind-operator/blob/master/README.md

**Comment by micgibso** [comment]
The sentence mentioned has been deleted, section now reads:
image

**Comment by micgibso** [comment]
`For more detailed information about the Codewind operator and the install process...` sentence added in step 1, cloning the repo, linking directly out to the Codewind operator readme.

**Comment by micgibso** [comment]
Added extra instructions for Windows, including prereq and note.

**Comment by AndyRWatson** [comment]
sorry @micgibso just a few more comments.

Prereqs.
#4 gitbash I don't think need to be called out as its actuall  installed with the git cli on windows.  We should just call out    

#4 Git command line client (inc gitbash for windows)

**Comment by AndyRWatson** [comment]
For section 1 - clone the codewind operator  repository

We just realised that we will need to version this in step with codewind releases.   This we will improve in 0.12 so for 0.11 we will need to add the extra branch information to insure the right operator is pulled so 

```$ git clone https://github.com/eclipse/codewind-operator -b 0.11.0 ```

@markcor11  can you confirm this will be enough for 0.11.0

**Comment by AndyRWatson** [comment]
2. Install the operator into your cluster and deploy Keycloak

For step two we only need the extra windows step for retrieving the keycloak

```$ kubectl get keycloak -n codewind

The command returns the following example output:

NAME       NAMESPACE   AGE    ACCESS
devex001   codewind    122m   https://codewind-keycloak-devex001.<ingress-domain>
```

The next steps to retrieve the equivalent codewind should be moved to the end of step 4 Deploy a Codewind instance

**Comment by AndyRWatson** [comment]
Prereq 4 is still referencing windows when its a prereq for all platforms 

```4. Git command line client installed```

and could maybe add the link to download https://git-scm.com/download

**Pull request merged**
