### PR TITLE
Adding links, removing file

### PR DESCRIPTION
**Pull request by sishida**
Signed-off-by: Sarah Ishida <sishida@us.ibm.com>

1️⃣ Added Tekton info section to remote-configuring.md.
2️⃣ Deleted the codewindandtektonpipelines.html file.

This PR applies to issues https://github.com/eclipse/codewind/issues/1542 and https://github.com/eclipse/codewind/issues/1536.

### CODE REVIEW

**Comment by tetchel** [comment]
This isn't my area

**Comment by sishida** [comment]
@micgibso I think you worked on writing up this original file, correct? Does this location seem appropriate for the Tekton information/links?

@tobespc I wasn't sure which people on the portal team would know this area best and/or who might have the bandwidth for review, so please feel free to reassign. :)

Thank you!

**Comment by micgibso** [comment]
@sishida I'll raise this with the Portal squad, thanks.

**Comment by micgibso** [comment]
Raised with Portal, the option to open the Tekton dashboard is within the IDEs and only appears if Tekton is installed. So please:
1. Delete the `codewindandtektonpipelines.md` file (this PR achieves that)

2. Delete the following `codewindandtektonpiplelines.md` lines from the table of contents file `docstoc.yml`, and keep the spacing between remaining sections nice and uniform:
     - title: 'Codewind and Tekton pipelines'
       url: codewindandtektonpipelines.html

3. To introduce the availability of the dashboard, add a new bullet entry to the `https://www.eclipse.org/codewind/mdt-vsc-commands-project.html` topic **Commands** section, and for Eclipse, the `https://www.eclipse.org/codewind/mdteclipsemanagingprojects.html` topic **Project actions** section, same bullet text for both as follows, suggested draft content: 

**Open Tekton Dashboard:**  This option is only available to you if you have installed pipelines. Use this option to open the dashboard.  

The bigger issue is one of naming as Rob has mentioned in https://github.com/eclipse/codewind/issues/1542. The **Open Tekton Dashboard** menu option should be renamed so we need to work with design and dev to achieve that. And then rename the text above to the new menu option.

**Comment by sishida** [comment]
@micgibso Thank you for the feedback. I have taken care of 1, 2, and 3 in this PR.

I'll remind design about eclipse/codewind#1542 and take care of name changes in the docs as part of 1542 after the names are changed by design/development.

**Comment by micgibso** [comment]
@sishida Lgtm. One more thing, we don't need to mention the Tekton dashboard in `remote-configuring.md` so all the changes to that file can be removed now we mention it in the IDE specific help.

**Comment by sishida** [comment]
Removing the following text from `remote-configuring`:

```
### Configuring Codewind for Tekton pipelines

Configure the Tekton dashboard in Codewind remote scenarios to use existing Tekton installations with Codewind.

To get started with the Tekton Dashboard Webhooks Extension, see [Getting started with the Tekton Dashboard Webhooks Extension](https://github.com/tektoncd/experimental/blob/master/webhooks-extension/docs/GettingStarted.md).

To access the Tekton dashboard, see the [Tekton dashboard README file](https://github.com/tektoncd/dashboard#install-on-openshift).
```

@micgibso Please approve if ready to merge.

**Comment by micgibso** [comment]
LGTM

**Pull request merged**
