### PR TITLE
News updates: Revise Che section and add ODO

### PR DESCRIPTION
**Pull request by micgibso**
Signed-off-by: micgibso <micgibso@uk.ibm.com>

### CODE REVIEW

**Comment by micgibso** [comment]
@elsony @geekarthur New PR for NEws revisions

**Comment by micgibso** [comment]
Related: https://github.com/eclipse/codewind/issues/605 and https://github.com/eclipse/codewind/issues/647

**Comment by micgibso** [comment]
Updated links in the code to point to `news05.html`, was `news04.html`.

**Comment by micgibso** [comment]
@elsony Thanks, have opened a new issue to address this: https://github.com/eclipse/codewind/issues/722

**Comment by GeekArthur** [comment]
Agree with Elson, the linking pages should be done by this PR: eclipse/codewind-docs#180, once the PR is merged then we can update the link to pages instead of issues.

**Pull request merged**
