### PR TITLE
Update Codewind on Che and Codewind Docker registry doc #1163

### PR DESCRIPTION
**Pull request by micgibso**
Signed-off-by: micgibso <micgibso@uk.ibm.com>

### CODE REVIEW

**Comment by micgibso** [comment]
@johnmcollier 
Hi John, Here's the PR for issue https://github.com/eclipse/codewind/issues/1163 which has the following points. Please review, can you suggest new info for where it's needed below too please? 

- Include OpenShift 4.x in step 3. Install Che:
	OpenShift is now included, please check.

- Under Creating the Codewind workspace with a Devfile section, update link https://raw.githubusercontent.com/eclipse/codewind-che-plugin/master/devfiles/0.4/devfile.yaml to https://raw.githubusercontent.com/eclipse/codewind-che-plugin/0.6.0/devfiles/0.6.0/devfile.yaml or point user to get the latest version
	Following recent updates, link currently goes to master, please check:
	https://raw.githubusercontent.com/eclipse/codewind-che-plugin/master/devfiles/0.6.0/devfile.yaml

- Remove Checking for the Codewind pod section
	Removed.

- Add a section on how to uninstall Che
	Reinstated and slightly updated the old uninstall topic that wasn't linked in, requires review.

- Add a section on how to update Che version
	Doesn't this update automatically when a newer version's available? If not, how would users do this?

- Add a section on how to configure source control such as GitHub in Che workspace so we can check in project code after creating/developing from the workspace.
	Help required for this also, how would users do this?

**Comment by johnmcollier** [comment]
The uninstall docs aren't accurate, I'll send updated instructions

**Comment by micgibso** [comment]
@johnmcollier Picking this up again today, you mentioned you were going to send some updated uninstall instructions,  did these make it into the docs or are they still required? 
Appreciate if you could take a look at the rest of this, including comments above, thanks.

**Comment by johnmcollier** [comment]
Uninstall:
- Codewind: 
   1) Go to the Che dashboard.
   2) Select the workspace where Che is running. Click the "Stop" button to stop the workspace. Then click the delete button to delete it.
- Che:
   1) Ensure you have an active Kube context to the cluster where Che is running.
   2) Run `chectl:server delete`

**Comment by micgibso** [comment]
@johnmcollier Thanks John, changes now on this PR. Just wanted to confirm that `chectl:server delete` is correct? Looking in `mdt-che-installinfo.md` start commands are of the format `chectl server:start` so from that format, one might expect the command to be `chectl server:delete`?

**Comment by johnmcollier** [comment]
@micgibso Ah, sorry you're right. Typo on my end.

It is `chectl server:delete`, just verified on my laptop.

**Comment by micgibso** [comment]
@johnmcollier Excellent, thanks, have updated the command.

**Comment by johnmcollier** [comment]
Docs look good to me, merging.

**Pull request merged**
