### PR TITLE
[Wip for 0.11.0] Document the remote operator

### PR DESCRIPTION
**Pull request by micgibso**
Signed-off-by: micgibso <MICGIBSO@uk.ibm.com>

PR for https://github.com/eclipse/codewind/issues/2464.

### CODE REVIEW

**Comment by micgibso** [comment]
@tobespc @AndyRWatson Please review, thx.

**Comment by AndyRWatson** [comment]
Some comments Michael from trying to walk through the documentation this morning

http://0.0.0.0:4321/codewind/remotedeploy-single.html
```For OpenShift, Codewind is required to run as privileged and as root because it builds container images. Run the following commands on OpenShift and IBM Cloud only. The <namespace> variable is the namespace into which you plan to install Codewind:

    Switch to your Codewind-only namespace using: oc project <Codewind-namespace>.
```

we have not asked the user to create a <codewind-namespace> at this stage.   We should include the 

```oc project namespace <codewind-namespace> ``` 
(we do have the commands later but that implies for only IBM Public Cloud ?)

we should also be consistant in the use of namespace,  in this section we refer to codewind-namespace and  also namespace.

**Comment by AndyRWatson** [comment]
```For IBM Public Cloud, you must install Keycloak and your remote Codewind in separate namespaces. Run the following commands where <namespace> is the namespace into which you plan to install Codewind:```

I am confused by the reference to  IBM public cloud,  as this section is not all-in-one so doesnt that infer always installing in two separate namespaces ie codewind -namespace and keycloak-namespace.  

Do we actually need to distinguish Kubernetes vs openshift here rather than calling out a vendor cloud ?  

As these commands all use 'oc'  these instructions are purely for Openshift , should there be kubernetes only instructions if the user is logged into Kubernetes (as referenced earlier 'Ensure you are logged into your Kubernetes or OpenShift cluster.' )

**Comment by AndyRWatson** [comment]
Determine your cloud ingress domain

running the example command 
```oc get routes -n default```
returns me 

```No resources found in default namespace.```

@markcor11 @tobespc can you confirm the command is correct

**Comment by AndyRWatson** [comment]
http://0.0.0.0:4321/codewind/remotedeploy-single.html#run-the-codewind-cli-command

In the example we create a keycloak in a namespace called keycloak-001.   In the prereq section we asked the user to create their own keycloak-namespace  For consistancy we should be referencing the keycloak-namespace in the example  if thats what we referenced earlier in the doc.

**Comment by AndyRWatson** [comment]
http://0.0.0.0:4321/codewind/remotedeploy-single.html#2-deploy-a-remote-codewind-service

first paragraph looks like it has a note "LIKE WHAT? WHICH ONES ARE REQUIRED? "

again the namespaces used in the examples should reflect the namespace the user used in the prereq section  codewind-namespace

Also for  **--kurl**  having   _https://_ before the codewind-keycloak url causes the install to fail.  I think it should be omitted in the same way that it has been omitted in the line before for **--ingress**

**Comment by AndyRWatson** [comment]
For step one in docs/_documentations/remote-install-operator.md.  could we not just say git clone the following repo and show the command.

Also later in the instructions we make a couple of references to 
```The Codewind operator default settings can be found in the [`https://github.com/eclipse/codewind-operator/blob/master/deploy/codewind-configmap.yaml`](https://github.com/eclipse/codewind-operator/blob/master/deploy/codewind-configmap.yaml) file. Save this file to your system.```

as we already git cloned the repo locally I dont think we need to save the files again and should be able to reference the files already cloned to the local file system  in ./deploy/........

**Comment by AndyRWatson** [comment]
in the deploy instructions we say 
```During deployment, the operator creates:
- A service account.
- A deployment.
- A pod.
- A service.
- An ingress or route.
- A self signed TLS certificate.
- A storage claim.
- Any secrets.

For example:
NAME                         SECRETS   AGE
codewind-keycloak-devex001   1         2m53s
NAME                                              READY   STATUS    RESTARTS   AGE
pod/codewind-keycloak-devex001-7454d4ff6c-fnrsr   1/1     Running   0          2m10s
NAME                                 TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
service/codewind-keycloak-devex001   ClusterIP   10.111.228.52   <none>        8080/TCP   2m10s
NAME                                         READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/codewind-keycloak-devex001   1/1     1            1           2m10s
NAME                                                    DESIRED   CURRENT   READY   AGE
replicaset.apps/codewind-keycloak-devex001-7454d4ff6c   1         1         1       2m10s
```
but do not show the command to show that output

**Comment by AndyRWatson** [comment]
by following the instructions docs/_documentations/remote-install-operator.md 

``` kubectl get keycloaks ```
gives 

``` no resources found ```

as we never documented to use the codewind namespace so likely still using default

the command should be 

```kubectl get keycloaks -n codewind```

where codewind was the configure / created namespace in the initial steps

**Comment by AndyRWatson** [comment]
For docs/_documentations/remote-deploy-instance.md we should suggest using the already cloned version of the files (as already downloaded for keycloak step of install ? @markcor11 ??) rather than saying save individual files ?

should also highlight any changes to names in the _./deploy/crds/codewind.eclipse.org_v1alpha1_codewind_cr.yaml_ file should be lowercase alphanumeric only

**Comment by AndyRWatson** [comment]
For docs/_documentations/remote-deploy-instance.md
```4. To list all running Codewind deployments together with the username of the developer to which each deployment is assigned, enter _kubectl get codewinds_```

should be kubectl get codewinds -n codewind (where codewind was the installed namespace) as we didnt ask the user to use the codewind namespace in previous steps

**Comment by AndyRWatson** [comment]
docs/_documentations/remote-install-operator.md 

some kubectl commands have ; on the end of the examples which are not correct

**Comment by micgibso** [comment]
Three questions in this draft, answered: 
1. remote_install_operator.md:1. Install the remote Codewind operator, do we need a log in step? 
2. remote-deploy-instance.md:
- The `loglevel` can be used to increase log levels of the Codewind pods. What other values are available for this?
3.  remote-deploy-instance.md:
- The `storageSize` field sets the PVC size to 10GB. Typical values? What's a good default?

**Comment by micgibso** [comment]
@AndyRWatson All comments addressed, thanks.

**Comment by micgibso** [comment]
Closing this PR to facilitate a new approach of pointing to the readme in the codewind-operator repo.

**Pull request closed without merging**
