### PR TITLE
Adding info about updating Codewind

### PR DESCRIPTION
**Pull request by sishida**
Signed-off-by: Sarah Ishida <sishida@us.ibm.com>

Adding info about updating Codewind for issue https://github.com/eclipse/codewind-docs/issues/113.

### CODE REVIEW

**Comment by sishida** [comment]
@johnmcollier, @sujeilyfonseca, @jagrag, Could you please review the doc updates for the new instructions in this PR? Please let me know if your section is good to go or if you'd like any additional changes. Thank you! :)

**Comment by sujeilyfonseca** [comment]
I reviewed the information to upgrade Codewind for VS Code, and everything looks good. I only have one comment. To be more accurate with the IDE, it would be good to include in Step 2:

- Select **More Actions...** > **Install from VSIX** and choose the `.vsix` file that corresponds to the latest images.

Thanks Sarah!

**Comment by jagraj** [comment]
Looks like for VSCode we need instructions from market place rather from "vsix" file. 
@sujeilyfonseca 
Could you please provide those updates to the doc.?

I believe users does not install from VSIX rather they do from market place.

**Comment by sujeilyfonseca** [comment]
Following Jag's comment, we just need to eliminate the second approach to the instructions. Therefore, Step 2 will look like this:

Search for the latest Codewind version in Marketplace.

**Pull request merged**
