### PR TITLE
Note on build status

### PR DESCRIPTION
**Pull request by makandre**
Signed-off-by: Andrew Mak <makandre@ca.ibm.com>

For https://github.com/eclipse/codewind/issues/2052

### CODE REVIEW

**Comment by makandre** [comment]
@sishida Could you review this PR?  It's for https://github.com/eclipse/codewind/issues/2052 where we're going to **not** display a build status for appsody projects (because it's misleading).

**Comment by sishida** [comment]
@makandre Should we specify what kind of projects won't display a build status? What do you think of a statement like this? "**Note:** Appsody projects do not display a build status."

**Comment by makandre** [comment]
@sishida I left it general in case some other projects won't show build status (maybe in future, tho unlikely).  I'm ok either way

**Comment by sishida** [comment]
@makandre I've made two commits with changes to specify Appsody projects. I would prefer to specify which kinds of projects so users won't wonder if the notes apply to their projects or not. If we get more projects that don't display status, it's easy to update the docs again and add them. :)

If these changes look good to go, we can merge! Thanks!

**Comment by makandre** [comment]
@sishida Sure, thanks for your edits.

**Pull request merged**
