### PR TITLE
Edits about offline usage

### PR DESCRIPTION
**Pull request by makandre**
Signed-off-by: Andrew Mak <makandre@ca.ibm.com>

For https://github.com/eclipse/codewind/issues/2444

Covers work done in https://github.com/eclipse/codewind/issues/2078 and https://github.com/eclipse/codewind/issues/2080

### CODE REVIEW

**Comment by makandre** [comment]
@sishida Please review.  I ended up making quite a bit of change, because I didn't want to sound as if there's an "offline" mode for Codewind and you can somehow "access" it.  Instead I wanted to frame it as: If you are offline, you can still work in Codewind given certain conditions

**Comment by sishida** [comment]
@makandre Thanks for clarifying that Codewind offline is just accessing Codewind when you're offline--not something you have to activate.

I've added a new commit with some changes. Does it look good to go?

**Comment by makandre** [comment]
@sishida Looks good!  (heads-up: once this is merged I'll need to port over to 0.10.0 docs)

**Comment by sishida** [comment]
@makandre We haven't created the 0.10.0 release branch for the docs yet. We plan to create docs release branches closer to GA. Thus, you shouldn't need to port anything to another branch. :)

**Pull request merged**
