### PR TITLE
Minor change to node.js and swift templates remain in starting state

### PR DESCRIPTION
**Pull request by j-c-berger**
Signed-off-by: Jacob Berger <jacob.berger@ibm.com>

For issue 1256: https://github.com/eclipse/codewind/issues/1256

### CODE REVIEW

**Comment by sghung** [comment]
@j-c-berger sorry about the delay. I tried it out and it is stuck in starting state. So I think the sub heading is correct, but not the content. I think something like this would be better:

The templates `Appsody Node.js template` and `Appsody Swift template` remain in starting state
 by default. These templates do not have a server and are intended to help you implement your own server.

**Comment by j-c-berger** [comment]
@sghung , new commit, reflecting your suggested changes. thanks.

**Comment by sghung** [comment]
Thanks, the changes look good. @j-c-berger can you make the same changes to 0.6.0 too? Thank you

**Comment by j-c-berger** [comment]
@sghung , sounds good. let me get to work on that after my lunch and afternoon meeting, thanks!

**Comment by j-c-berger** [comment]
@sghung see my new PR 246 for changes for 0.6.0 branch: https://github.com/eclipse/codewind-docs/pull/246

**Pull request merged**
